### ISSUE TITLE
Phone numbers in paper

### ISSUE THREAD

**Issue by shengwu** [bjlange/judgit#1]
I've been trying to cut down on robocalls, and noticed that the paper in the `gh-pages` branch of this repo has our phone numbers. 

I don't know if this is where spammers are getting my number, but I wonder if recreating the pdf without the phone numbers would help.

**Comment by bjlange** [comment]
Doubt it, but I'll upload a number-less version just for you :)

**Comment by shengwu** [comment]
appreciate it brian!
